---
name: Lint Code Base
on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSIBLE_DIRECTORY: /ansible
          VALIDATE_MD: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
